/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define REGISTRAR 4334
#define REGISTRARVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC_DATE 1
extern  enum clnt_stat rpc_date_1(char *, int *, CLIENT *);
extern  bool_t rpc_date_1_svc(char *, int *, struct svc_req *);
extern int registrar_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC_DATE 1
extern  enum clnt_stat rpc_date_1();
extern  bool_t rpc_date_1_svc();
extern int registrar_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
